// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcjG8itdcHOj5G1_PZ9WEcUF3seEfDSRo',
    appId: '1:58041429703:web:1659ddc5e248d5c8f758e2',
    messagingSenderId: '58041429703',
    projectId: 'flutter-firebase-6b69b',
    authDomain: 'flutter-firebase-6b69b.firebaseapp.com',
    storageBucket: 'flutter-firebase-6b69b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRRMKZENcyR1x883n0DVVH6amUmVZ515M',
    appId: '1:58041429703:android:aaf0109a9a7edaa4f758e2',
    messagingSenderId: '58041429703',
    projectId: 'flutter-firebase-6b69b',
    storageBucket: 'flutter-firebase-6b69b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQmoSzNG0Kw_FrsNnhMdbtJVzyGGRc70w',
    appId: '1:58041429703:ios:7341d454b832a011f758e2',
    messagingSenderId: '58041429703',
    projectId: 'flutter-firebase-6b69b',
    storageBucket: 'flutter-firebase-6b69b.appspot.com',
    androidClientId: '58041429703-0e6n9sdjr8r7co2567iopildubhie68s.apps.googleusercontent.com',
    iosClientId: '58041429703-ibfetleeco1ln0pb7vngqdufp8dbs1ct.apps.googleusercontent.com',
    iosBundleId: 'com.example.week2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQmoSzNG0Kw_FrsNnhMdbtJVzyGGRc70w',
    appId: '1:58041429703:ios:7341d454b832a011f758e2',
    messagingSenderId: '58041429703',
    projectId: 'flutter-firebase-6b69b',
    storageBucket: 'flutter-firebase-6b69b.appspot.com',
    androidClientId: '58041429703-0e6n9sdjr8r7co2567iopildubhie68s.apps.googleusercontent.com',
    iosClientId: '58041429703-ibfetleeco1ln0pb7vngqdufp8dbs1ct.apps.googleusercontent.com',
    iosBundleId: 'com.example.week2',
  );
}
